permalink: /:year/:month/:day/:title.html
markdown: kramdown
pygments: true

kramdown:
  input: GFM

# 作者信息
author: 
  name: linglong102
  email: 102140203@qq.com
  link: http://linglong102.github.io/
  weibo: 
  github: https://github.com/linglong102

# 站点信息
title: linglong102的博客 
description: 张玲珑的博客
url: http://linglong102.github.io/
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: https://raw.githubusercontent.com/linglong102/linglong102.github.io/master/avatar.png
favicon: https://raw.githubusercontent.com/linglong102/linglong102.github.io/master/favicon.png

# google analytics 设置
ga:
  id: 
  url: 

# disqus 设置
disqus:
  shortname: linglong102githubblog

# 主题设置，自动激活某个标签
active: 技术

# 首页除了最新文章外显示分类
cates: 
  - zabbix
  - KVM虚拟化
  - openstack

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
  content: 目录
