permalink: /:year/:month/:day/:title.html
markdown: kramdown
pygments: true

kramdown:
  input: GFM

# 作者信息
author: 
  name: Barry
  email: 1005437573@qq.com
  link: http://barrybaby.github.io/
  weibo: 
  github: https://github.com/Barrybaby

# 站点信息
title: Barry的博客 
description: Barry的博客
url: http://barrybaby.github.io/
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: https://raw.githubusercontent.com/Barrybaby/Barrybaby.github.io/master/avatar.png
favicon: https://raw.githubusercontent.com/JerryBaby/jerrybaby.github.io/master/favicon.png

# google analytics 设置
ga:
  id: 
  url: 

# disqus 设置
disqus:
  shortname: Barrybabygithubblog

# 主题设置，自动激活某个标签
active: 技术

# 首页除了最新文章外显示分类
cates: 
  - Git
  - Pxe+kickstart
  - Information

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
  content: 目录
